<?php

namespace CustomMixtapes\Mikandi\Comics;

use Mixtapes\Mixtape;
use Mixtapes\TrackList;

class Comic Extends Mixtape {

    private $tracklist;

    public function __construct()
    {
        $this->tracklist = new TrackList();
        $this->mixtapeName = __CLASS__;
        $this->description = "Hi There. Welcome to my Comic Mixtape. Below you will find the tracks that are in this mixtape. They show you the stuff that you need. <h1>Remember Mixtapes must be self contained and be modular.</h1>"
            ."<br/> Here is the documentation: Wha?????? Documentation: <br/>  <br/> <a href='http://www.mixtape.com/documentation/mixtapes/mixtape/comic'>Comic Mixtape Documentation</a>";
        $this->trackList[] = array("Method" => "listAllComics()", "Description" =>  "This method is used to get all the comics from comic API and return a JSON object");
        $this->trackList[] = array("Method" => 'comic(int $id)', "Description" =>  'Get a comic by its id as $int. Returns a Json Object');

    }

    public function ListTracks()
    {
        parent::ListTracks(); // TODO: Change the autogenerated stub
    }

    public function listAllComics(){
        echo "all the comics";
    }

}